### PR TITLE
Added optional bounce on close

### PR DESCRIPTION
**Pull request by justinmakaila**
added property and check to make bouncing on close optional

### CODE REVIEW

**Comment by 0xdevalias** [comment]
Re: #68

**Comment by stuffmc** [comment]
Hey @gotosleep would you please pull this one? :) Appreciated. Thanks.

**Comment by gotosleep** [comment]
`bounceOnSidePanelClose` is actually used to toggle something slightly different, so I ended up creating a new flag, `self.bounceOnCenterPanelChange = YES;` Thanks for the pull request!

**Comment by stuffmc** [comment]
Great! Thanks!

**Pull request merged**
