### PR TITLE
Creating JASidePanelController from storyboard

### PR DESCRIPTION
**Pull request by tracy**
I had to make this small change to support creating JASidePanelController from my storyboard. Thought it might be useful to others. Thanks for the project, I got it set up quickly today and it looks great so far!

### CODE REVIEW

**Comment by gotosleep** [comment]
Thanks Tracy!

**Comment by olivierto** [comment]
how did you do to make it work in storyboard? I don't get it!

Thanks in advance.

**Comment by tracy** [comment]
I don't do anything too special with it in the storyboard, but since all my other view controllers are there it's convenient for me to have it represented there. I just dragged a new ViewController onto the storyboard and set its type to JASidePanelController. I also checked the "Is Initial View Controller" box.

In application:didFinishLaunchingWithOptions: I reference it like this: 

```
JASidePanelController *sidePanelController = (JASidePanelController *)self.window.rootViewController;
```

and then set up all its view controllers. 

If the side panel controller isn't the main navigation for your app, your setup might be a little different. Hope that helps!

**Comment by olivierto** [comment]
thank you! and sorry for the late reply!
it works!

**Comment by tracy** [comment]
Glad to hear it!

**Comment by adi101010** [comment]
Tracy could you please give the full application:didfinishLaunchingWithOptions:, i m a bit confused.
I am just learning storyboards. 

Thank you in advance.

**Pull request merged**
