### PR TITLE
Fix leftVisibleWidth and rightVisibleWidth

### PR DESCRIPTION
**Pull request by 0xdevalias**
Would always return 0 when left/rightFixedWidth not set.

This fix defaults the left/rightFixedWidth to NaN, and then tests to ensure an actual value is set before returning it.

The method that was being used doesn't work for floats (will always return true regardless)

### CODE REVIEW

**Comment by gotosleep** [comment]
Hey Alias, I don't see a problem with the current code. Objective-C initializes instance variables to 0 and 0 is false. So, self.leftFixedWidth & self.rightFixedWidth are only returned if they are set to something non-0.

**Comment by 0xdevalias** [comment]
My tests would seem to indicate otherwise given this logic. I tested both through the current library and seperating out the relevant functionality, and in both cases when the variables are unset, those functions evaluate as true and return 0. My understanding is that in this case the intention is for it to evaluate as false, and return the else?

**Comment by gotosleep** [comment]
Strange, I just tested again and I am seeing different behavior from you. What version of XCode are you using? `0` is definitely false in Objective-C. In fact, until recently, `NO` was just a `#define` for `0` 

> Previously, the BOOL type was simply a typedef for signed char, and YES and NO were macros that expand to (BOOL)1 and (BOOL)0 respectively. To support @YES and @NO expressions, these macros are now defined using new language keywords in &LT;objc/objc.h&GT;:

```
#if __has_feature(objc_bool)
#define YES             __objc_yes
#define NO              __objc_no
#else
#define YES             ((BOOL)1)
#define NO              ((BOOL)0)
#endif
```

from http://clang.llvm.org/docs/ObjectiveCLiterals.html

**Comment by 0xdevalias** [comment]
I'll have to check exact versions/etc when I get home (Edit: Version 4.6 (4H127)), and for the sake of argument shall rewrite the tests and see if I still run into it. Ran into this when developing an app, so I know it definitely happened in a real world situation.

Quickly found this on google though, which seems to indicate float (CGFloat) isn't guaranteed 0 when uninitialized:
  http://red-glasses.com/index.php/iphone/apples-c-compiler-llvm-doesnt-set-float-to-0-0-why-not/

Similarly, the issue here seems to be caused by the same thing: http://stackoverflow.com/questions/7518686/declared-but-unset-variable-evaluates-as-true

**Comment by 0xdevalias** [comment]
Ok, knocked up a quick test to just display them and they are working fine now, so that confirms what you're seeing. Given that an uninitialized float's behaviour is undefined (depends what the memory was like before), I still believe this is an issue (potentially an even more annoying one since it only happens sometimes)

Are there any negative effects/detriments from implementing the change as I've coded it?

**Comment by gotosleep** [comment]
@alias1, what your links fail to mention is that that behavior is only true for local variables. Objective-C always initializes all instance variables to 0/nil in the alloc method:

> alloc
> Returns a new instance of the receiving class.
> - (id)alloc
>   Return Value
>   A new instance of the receiver.
> 
> Discussion
> The isa instance variable of the new instance is initialized to a data structure that describes the class; **memory for all other instance variables is set to 0**.

[source](https://developer.apple.com/library/iOs/#documentation/Cocoa/Reference/Foundation/Classes/NSObject_Class/Reference/Reference.html)

Also, a stackoverflow post on this topic: http://stackoverflow.com/questions/990817/are-ints-always-initialized-to-0

Additionally, your bug report contains conflicting information. If leftFixedWidth/right were actually set to garbage, they wouldn't return 0, they would return the garbage they contain.

I'm not going to merge the change because:
1. It is fixing a non-existant bug
2. Personally, I feel the modified code is less intuitive/readable than the current code

**Comment by 0xdevalias** [comment]
Fair call. If I run into the issue again I'll try to get some more contextual evidence as to what's going on so as to debug better. :)

**Pull request closed without merging**
