### PR TITLE
Send NSNotifications when panels are shown

### PR DESCRIPTION
**Pull request by rnystrom**
I added NSNotifications after the left, right, and center panels are shown. I needed the ability to add listeners to dismiss the keyboard when a panel is swiped.

### CODE REVIEW

**Comment by gotosleep** [comment]
It's not obvious, but you can actually use KVO on the `state` property to monitor state changes. I use this in my apps quite a bit.

Here's an example

```
- (id)init {
    if (self = [super init]) {
        [[SCSidePanelController mainController] addObserver:self forKeyPath:@"state" options:NSKeyValueObservingOptionInitial context:nil];
    }
    return self;
}

- (void)dealloc {
    [[SCSidePanelController mainController] removeObserver:self forKeyPath:@"state"];
}

#pragma mark - KVO

- (void)observeValueForKeyPath:(NSString *)keyPath ofObject:(id)object change:(NSDictionary *)change context:(void *)context {
    if ([keyPath isEqualToString:@"state"]) {
        // do something
    }
}

```

As for adding a delegate: I've thought about it, but I'm actually not a huge fan of the delegate pattern & haven't really found a need to add it yet.

**Comment by 0xdevalias** [comment]
Purely hypothetically, would there be any harm in adding it for others sake? (understanding full well that you're not a fan of it) Also, maybe add that info from your last post somewhere to make it easier to find? (readme/wiki?)

**Comment by wuf810** [comment]
Sorry but I don't get it. 

How does observing the state tell me which panel is about to appear or when it has animated into place. It tells me the current state at the point you set the state and no more.

Developers need to fine grain control and I think you need to re-consider one of the other options and possibly just accept one of the various Pull requests been offered.

Thanks, M.

**Comment by danielkramer** [comment]
I have the KVO state monitoring working in an earlier version of your code, I've recently updated and now I'm getting the following crash on startup.

 **\* Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: '<MainSideViewController: 0x10c5aca0>: An -observeValueForKeyPath:ofObject:change:context: message was received but not handled.
Key path: state
Observed object: <MainSideViewController: 0x10c5aca0>
Change: {
    kind = 1;
}
Context: 0x0'

Any Ideas? Here's what I'm doing:

I'm subclassing JASidePanelController, in my viewDidLoad I have:

```
[self addObserver:self forKeyPath:@"state" options:NSKeyValueObservingOptionInitial context:nil];
```

and as part of my subclass I have:

```
- (void)observeValueForKeyPath:(NSString *)keyPath ofObject:(id)object change:(NSDictionary *)change context:(void *)context {

[super observeValueForKeyPath:keyPath ofObject:object change:change context:context];

if ([keyPath isEqualToString:@"state"]) {

#ifdef FREE_VERSION
        [self animateAdView];
#endif
        [self animateStatusView];
    }
}
```

Thanks for any tips

Daniel

**Comment by danielkramer** [comment]
Ah.. looks like if I comment out your context check:

```
if (context == &ja_kvoContext)
```

The crash disappears.  Any pointers on the right way to do this? I'm not very familiar with KVO

**Comment by shams-ahmed** [comment]
@danielkramer did you solve the issue am getting the same issue? i don't want to modifier the JASider code...

**Comment by shams-ahmed** [comment]
ok i solved the issue wrote the code wrong try this:
addObserver:
  [self.viewController addObserver:self forKeyPath:@"state" options:NSKeyValueObservingOptionInitial context:nil];

add method on any class:
-(void)observeValueForKeyPath:(NSString *)keyPath ofObject:(id)object change:(NSDictionary *)change context:(void *)context {
    if ([keyPath isEqualToString:@"state"]) {
        NSLog(@"Center: %@ %@ %@ %@", keyPath, object, change, context);
    }
}

**Comment by danielkramer** [comment]
@shams-ahmed I did solve it.  I changed to:

```
- (void)observeValueForKeyPath:(NSString *)keyPath ofObject:(id)object change:(NSDictionary *)change context:(void *)context {

    if ([keyPath isEqualToString:@"state"]) {

    #ifdef FREE_VERSION
        [self animateAdView];
    #endif
        [self animateStatusView];
    }

    else {
        [super observeValueForKeyPath:keyPath ofObject:object change:change context:context];
    }

}
```

So I ended it up only calling the super class if it doesn't match what I'm looking for

D

**Comment by xsoti** [comment]
I just added [self.centerPanel viewWillAppear:NO]; in - (void)setState:(JASidePanelState)state method for case that I needed

**Pull request closed without merging**
