### PR TITLE
Add callbacks to panels before and after becoming active/inactive

### PR DESCRIPTION
**Pull request by uranusjr**
Added a protocol for panels that contains four optional methods:

```
- (void)willBecomeActiveAsPanelAnimated:(BOOL)animated withBounce:(BOOL)withBounce;
- (void)didBecomeActiveAsPanelAnimated:(BOOL)animated withBounce:(BOOL)withBounce;
- (void)willResignActiveAsPanelAnimated:(BOOL)animated withBounce:(BOOL)withBounce;
- (void)didResignActiveAsPanelAnimated:(BOOL)animated withBounce:(BOOL)withBounce;
```

These are called (if the panel has implementation) in `_showRightPanel:bounce:`, `_showLeftPanel:bounce:` and `_showCenterPanel:bounce:`. This enables the side panel to be notified when the state changes.

### CODE REVIEW

**Comment by rnystrom** [comment]
I might be able to see the value in this if something other than the view controller was the delegate as view controllers respond to -viewWillAppear:animated:, etc. 

I would recommend changing the name of the protocol to `JASidePanelDelegate` though. `JASidePanel` is a bit vague.

**Comment by uranusjr** [comment]
I used these callbacks to get notified when panels are activated/deactivated. `-viewWillAppear:` and others don't work as expected for panels because they are not always technically "hidden" when they are out of sight, and the current master implementation doesn't offer a good way to let other controllers notified.

But you're right, I should make the callbacks behave in a more generic way. I'll revise this (along with the name change) ASAP. Thanks.

**Comment by marzapower** [comment]
+1 for this pull request. `JASidePanel` seems fine, since it's not a delegate for the panel controller, but it's the panel itself.

**Comment by mpurland** [comment]
+1 for this pull request.  I agree with that @uranusjr that it should behave in a more generic way.

**Comment by uranusjr** [comment]
Sorry, other things caught up on me and I had completely forgot about this one before @marzapower brought it up. I have considered some options since then, but have not been able to come up with a satisfying approach "generalizing" the delegate methods.

The obvious approach is to change the protocol name to `JASidePanelControllerDelegate` (or something similar), set up a delegate property in `JASidePanelController`, and dispatch something like `-controller:willSwitchFromPanel:toPanel:animated:withBounce:` and others when appropriate. But this would be **worse** than my current approach in normal use cases, since you can only have one delegate at a time, and would need additional subclassing and/or a helper object to keep multiple panels informed about their status, which is not only inconvenient but also (IMHO) violates MVC big time. Not a reasonable option.

I do, however, find another way to achieve what I was looking for at the first place. To trigger the `-viewWillAppear:` and others correctly, all we need to do is to remove the panels when they do out of sight. The center panel already works as expected when you hide/show it, so all we need to do is to remove the left and right side panels when they go out of sight, and add them back when they are to appear. After inspecting the code I find that the `-addSubview:` calls are already called when necessary, so all I need to do is to override one synthesized setter:

```
- (void)setVisiblePanel:(UIViewController *)visiblePanel
{
    if (_visiblePanel != _centerPanel)
        [_visiblePanel.view removeFromSuperview];
    _visiblePanel = visiblePanel;
}
```

Note that the center panel needs to be treated as a special case. By removing side panels from the view hierarchy, `-viewWillAppear:` and related will work as expected on the side panels' view controllers.

I'm not sure if I missed something. If not, I'll just close this request and submit a new one with the above modification.

p.s. One thing worth noted about this approach is that the center panel won't be able to be notified when it resigns activeness to one of the side panels (but not removed). Adding the delegate actually fixes this, but I don't think it is even necessary.

**Comment by mpurland** [comment]
@uranusjr This seems like an agreeable approach since delegates wouldn't be needed then and the normal viewWillAppear method would work.  Would this also work for viewDidAppear?

**Comment by uranusjr** [comment]
Yes -- if I code everything correctly. I might not be able to report back very soon since I have little spare time working on iOS recently. I will try to make sure everything is called correctly before releasing the patch.

**Comment by cschubiner** [comment]
What's the progress on this? This is a very valuable update that should be included asap.

**Comment by uranusjr** [comment]
Unfortunately I'm finding great difficulties committing enough time on this. My works are now much less  focused on iOS, and there are already some other libraries that suits my (original) need. I will continue trying to find time for time, but in the mean time please feel free to submit your own PR based on this one if you wish to. I'll close this to reflect the current status. Sorry for any inconvenience.

**Pull request closed without merging**
